# Generated by Django 4.0 on 2022-01-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_globalmessage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmessage',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
