# Generated by Django 4.0 on 2022-01-03 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0004_privateroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proom', to='chat.privateroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puser', to='auth.user')),
            ],
        ),
    ]
