# Generated by Django 4.0 on 2022-01-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0006_privateroom_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroom',
            name='type',
            field=models.CharField(choices=[('INDIV', 'indiv'), ('GROUP', 'group')], default='group', max_length=5),
        ),
        migrations.AlterField(
            model_name='privateroom',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_admin', to='auth.user'),
        ),
    ]
